"""
Dictionary structure:
Key: corresponds to a class to be predicted
Value: corresponds to a prompt text which will be feeded to clip 
"""

room_label_and_prompt = {
    "Basement": [
        "A photo of an empty basement",
    ],
    "Bathroom": [
        "A photo of a Bathroom",
    ],
    "Bedroom": ["A photo of a bedroom"],
    "Garage": [
        "A photo of a Garage",
    ],
    "Garden/Yard": [
        "A photo of a Garden with flowers and trees",
    ],
    "Gym": [
        "A photo of a Gym or persons doing excercise for fitness",
    ],
    "Kitchen": [
        "A photo of a Kitchen",
    ],
    "Children's Room": [
        # 'A photo of a child in a children room',
        # 'A photo of a children room with toys',
        # 'A photo of a bedroom with fluffy toys',
        # 'A photo of a children room with bunk bed',
        # 'A photo of a children room with painting',
        "a photo of a children room with bed.",
        "a photo of a children room with cradle.",
        "a photo of a childs room.",
        "a photo of the childs room.",
    ],
    "Living Room": [
        # 'A photo of a living room with sofas',
        # 'A photo of a living room with sofas and fireplace',
        # 'A photo of a living room with sofas and fireplace and LED',
        # 'A photo of a living room with windows and sofas',
        # 'A photo of a living room with stairs and windows',
        "a photo of a basement living room with stairs and windows.",
        "a photo of a living room with no fireplace.",
        "a photo of a living room.",
        "a photo of the living room.",
    ],
    "Office": [
        # 'A photo of an office', 'A photo of a home office',
        # 'A photo of a home office with lower ceiling, rotating chair and LED',
        # 'A home office with lower ceiling, rotating chair and LED',
        # 'A photo of home room with large space and LED',
        # 'A photo of a condo office',
        # 'A photo of a condonium office',
        # 'A photo of an office room with books',
        # 'A photo of a room with large space and LED',
        # 'A photo of a living room with large space, office chair and LED',
        # 'A photo of room with office chair and desk',
        # 'A photo of a room with office chair, laptop and desk',
        # 'A photo of a person working in office with study desk and chair',
        # 'A photo of an office with chairs and working desk',
        # 'A photo of rotating chair and desk and windows',
        "A living room with a desk, chair, and a bookcase",
    ],
    "Dining Room": [
        "A photo of persons in dining room eating food on dining table",
        "A photo of a dining hall",
        "A photo of a dining room with chair dining table",
        "A photo of a dining hall with no book",
    ],
    "Informal Dinning Room": [
        "a photo of a kitchen with a dinning table.",
        "a photo of a kitchen with a eating place.",
    ],
    "Closet": [
        # 'a photo of the big wardrobe.',
        # 'a photo of the small wardrobe.',
        # 'a photo of the small closet.',
        # 'a photo of the big closet.',
        # 'a photo of the big closet.',
        "a photo of a closet.",
        "a photo of a wardrobe.",
    ],
    "Garden w/pool": [
        "A photo of a Swimming Pool",
    ],
    "Game Room": [
        "a photo of a game room with a gaming chair and gamming computers.",
    ],
    "Library/Study": [
        "A photo of a library",
    ],
    "Balcony": [
        "A photo of a balcony with potted plants",
    ],
    "Laundry Room": [
        "A photo of a Laundry with washing machines or clothes",
    ],
    "Loft": [
        "A photo of a garret with large space, lower ceiling and stairs",
    ],
    "Wine Cellar": [
        "A photo of a Wine Room",
    ],
    "Bar": [
        "A photo of a Bar",
    ],
    "Terrace": [
        "a photo of a terrace.",
        "a photo of a terrace without glass walls or dome.",
    ],
    "Storage Room": [
        "A photo of a storage room for extra stuff",
    ],
    "Empty Room": [
        "A photo of a Empty Room",
    ],
    "Cinema Room": [
        "A photo of a cinema room",
    ],
    "Lobby": ["A photo of a lobby"],
    "Workshop": [
        "a photo of a workshop with some tools, equipments and some storage room for extra space",
        "a photo of a workshop with some tools, equipments",
        "a photo of a storage space of a mechanic",
        "mechanic workshop",
    ],
    "Gazebo": [
        "a photo of a wooden gazebo." "a photo of a gazebo exterior.",
        "a photo of a gazebo.",
        "a photo of a pavilion.",
        "a photo of a patio in the style of a gazebo.",
        "a photo of a gazebo with a pool in backyard.",
        "a photo of a gazebo on a terrace.",
        "a photo of a hexagonal gazebo.",
        "a photo of a hexagon canopy gazebo.",
        "a photo of an outdoor sitting on a terrace with some shelter.",
    ],
    "Mud Room": [
        "a photo of a mud room.",
        "a photo of a utility room.",
        "a photo of a closet or wardrobe with a coat rack.",
        "a photo of a a closet or wardrobe with a coat stand.",
        "a photo of a a closet or wardrobe with a hatrack.",
        "a photo of a a closet or wardrobe with a hatstand.",
        # 'a photo of an utility room with a closet and wall mounts.',
        # 'a photo of an utility room with a wardrobe and wall mounts.',
        # 'a photo of the utility room.',
        # 'a photo of a mud room with a wardrobe.',
        # 'a photo of a mud room with a wardrobe.',
        # 'a photo of the mud room with a wardrobe.',
        # 'an entrance of a house with closet',
        # 'a closet for outwear, shoes near an entrance',
        # 'a closet with basket for shoes',
        "a photo of a utility room with wall mounts.",
    ],
    "Billiard Room": [
        "a photo of a billiard room.",
        "billiard game",
        "billiard table in library",
    ],
    "Spa/Sauna Room": [
        "an spa",
        "an spa bed",
        "an massage bed with massage oils, lotions and towels",
        "an high bed for massage",
        "a bedroom with towels",
        "a narrow bed for massage",
        "massage table",
        "massage chair with massage table",
        "an sauna",
        "a photo of an saunat",
        "sauna with a glass door in a bathroom",
        "wooden room with benches",
    ],
    "Athletic Court": [
        "an atheletic court",
        "squash court",
        "players playing in court",
        "an basketball court",
        "basket of basketball",
        "an outdoor atheletic court",
        "table tennis game",
    ],
    "Pantry": [
        "pantry",
        "storage room with canisters, water bottles, oil jugs, plate rack, spices box or meal box",
        "kitchen rack with canisters, water bottles, oil jugs, plate rack, spices box or meal box",
        "storage room for kitchen stuff",
        "storage racks for kitchen stuff",
        "an closet for kitchen stuff",
        "a walk in storage space of pantry",
    ],
    "Porch": [
        "porch",
    ],
    "Conservatory": [
        "a photo of a conservatory.",
        "a photo of the conservatory.",
        "a photo of a greenhouse.",
        "a photo of the greenhouse.",
        "a photo of a greenhouse indoor.",
        "a photo of the greenhouse indoor.",
        "a photo of a greenhouse outdoor.",
        "a photo of the greenhouse outdoor.",
        "a photo of a sunroom.",
        "a photo of a sunroom indoor.",
        "a photo of a sunroom outdoor.",
        # 'glass-enclosed atrium',
        # 'glass-enclosed sunroom',
        # 'a glass dome room',
        # 'a photo of a room with glass walls and dome.',
        "a photo of a dining room with glass dome and walls.",
        "a photo of a glass-enclosed atrium on a terrace.",
        # 'sunroom',
        # 'dinning room in a conservatory',
    ],
    "Studio": [
        "studio room",
        "a studio room with audio console",
        "a studio room with mixing console",
        "a studio room with audio console, gaming chair, and screen",
        "a studio room with studio mixers",
        "a studio room with midi controllers",
        "a studio room with digital audio workstations",
        "a studio room with outboard gear",
        "a studio room with piano",
    ],
    # 'Media Room': [
    #     'a view of a living room with couch and a flat screen or television',
    #     'room with a large screen tv and leather recliners',
    #     'a view of a living room with a couch and a flat screen tv',
    #     'room with a couch, chair, table, and a projector screen',
    # ],
    "Patio": [
        # 'outdoor living',
        # 'outdoor seating',
        # 'a patio with couch',
        # 'a patio in a terrace with couch',
        "a photo of a courtyard.",
        "a photo of a patio with fire pit and chairs under a canopy.",
        "a photo of a restaurant patio.",
        "a photo of the restaurant patio.",
        "a photo of a patio.",
        "a photo of the patio.",
        # 'a patio under a canopy',
        "a photo of a patio on a terrace.",
    ],
    "Hearth Room": [
        # 'hearth room',
        "a living room with a fireplace or a chimney.",
        # 'a living room with a hearth',
    ],
    "Deck": [
        "deck",
    ],
    "Play Room": [
        "a photo of a playroom.",
        "a photo of the playroom.",
        "a photo of a child play room.",
        "a photo of a child room with toys.",
    ],
    # 'Breezeway': [
    #     'breezeway',
    #     'covered walkway',
    #     'outdoor corridor',
    #     'sheltered pathway',
    #     'weather-protected pathway'
    # ],
    "Computer Room": [
        "a photo of a computer room.",
        "a photo of the computer room.",
        "a photo of the computer room with chairs.",
    ],
    "Amusement Room": [
        "a photo of an amusement arcade.",
        "a photo of the amusement arcade.",
        "a photo of a amusement room.",
        "a photo of a amusement room with indoor games.",
    ],
}
